# Jupytext Configuration
# Keeps .md files as source of truth, generates .ipynb in _build/ directory

# Default formats for notebooks directory
[formats]
"notebooks/" = "md:myst"           # Source format (version controlled)
"notebooks/_build/" = "ipynb"      # Generated notebooks (gitignored)

# Sync options
[sync]
# Only sync when explicitly requested
# This prevents automatic .ipynb creation on every .md save
auto_sync = false
