name: Deploy Documentation

on:
  push:
    branches: [main, master]
    paths:
      - 'docs/**'
      - 'notebooks/**'
      - 'src/hellocloud/**'
      - '.github/workflows/docs.yml'
  pull_request:
    paths:
      - 'docs/**'
      - 'notebooks/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.8.25

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install dependencies
        run: |
          uv sync --all-extras
          uv pip install -e .

      - name: Execute notebooks with outputs
        run: |
          just nb-execute-all

      - name: Generate API Reference
        run: |
          uv run quartodoc build --config docs/_quarto.yml

      - name: Render Documentation
        run: |
          quarto render docs/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site

  deploy:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
